In [1]:
import numpy as np

In [2]:
# define two pairs of vectors
x1 = np.array([1,1,1,-1])        # x1 and x2 represent input patterns
y1 = np.array([1,-1])
x2 = np.array([-1,-1,1,1])
y2 = np.array([-1,1])

In [3]:
# compute weight matrix W
print(np.outer(y1,x1))
print()
print(np.outer(y2,x2))

[[ 1  1  1 -1]
 [-1 -1 -1  1]]

[[ 1  1 -1 -1]
 [-1 -1  1  1]]


In [4]:
W = np.outer(y1,x1) + np.outer(y2,x2)
print(W)

[[ 2  2  0 -2]
 [-2 -2  0  2]]


In [5]:
# define BAM function
def bam(x):
    y = np.dot(W,x)
    y = np.where(y >= 0,1,-1)
    return y

In [6]:
# test BAM with inputs
x_test = np.array([1,-1,-1,-1])
y_test = bam(x_test)

In [7]:
# print output
print("Input x: ", x_test)
print("Output y: ", y_test)

Input x:  [ 1 -1 -1 -1]
Output y:  [ 1 -1]


In [8]:
print(W @ x_test)

[ 2 -2]
